### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by jiangjiatao** [thundersdata-frontend/rn-template#24]
![image](https://user-images.githubusercontent.com/18566483/138799005-fcfb2f63-2686-4c49-993f-753affca2ebe.png)
路径明明是存在的，为啥会显示不存在，导致运行不起来

**Comment by chj-damon** [comment]
好的，谢谢反馈，我在我本地复现一下

**Comment by chj-damon** [comment]
在你的babel.config.js里面，找到rn-hooks的配置，改成下面的：
```js
    [
      'import',
      {
        libraryName: '@td-design/rn-hooks',
        libraryDirectory: 'lib/module',
        camel2DashComponentName: false, // 增加这一句
      },
      'hooks',
    ],
```

**Comment by jiangjiatao** [comment]
@chj-damon 可以了，app里面居然是空的。。。。

**Comment by chj-damon** [comment]
这只是一个模板，目的是想省去搭建环境的工作，同时具备一些最基础的页面，方便基于此快速开发业务，所以模板里面的内容并不多。
