### ISSUE TITLE
克隆项目到本地，安装依赖后运行 yarn android:dev 报错

### ISSUE THREAD

**Issue by Atlan8** [thundersdata-frontend/rn-template#25]
环境： Mac OS 12.0.1

yarn run v1.22.10
$ react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1397 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...

> Configure project :app
Reading env from: .env

> Task :react-native-image-picker:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
212 actionable tasks: 2 executed, 210 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-image-picker:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':react-native-image-picker:debugCompileClasspath'.
   > Could not download annotation-1.1.0.jar (androidx.annotation:annotation:1.1.0)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/annotation/annotation/1.1.0/annotation-1.1.0.jar'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/annotation/annotation/1.1.0/annotation-1.1.0.jar'.
            > dl.google.com:443 failed to respond

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-image-picker:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':react-native-image-picker:debugCompileClasspath'.
   > Could not download annotation-1.1.0.jar (androidx.annotation:annotation:1.1.0)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/annotation/annotation/1.1.0/annotation-1.1.0.jar'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/annotation/annotation/1.1.0/annotation-1.1.0.jar'.
            > dl.google.com:443 failed to respond

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s

**Comment by chj-damon** [comment]
我在本地试了一下，没有发现问题。
建议你开一下翻墙，然后更新一下项目再重新试试看

**Comment by Atlan8** [comment]
开了翻墙变成下面的报错了：

yarn run v1.22.10
$ ENVFILE=.env.dev react-native run-android
warn Package lint-staged has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/shiyanghua/practice/rn-template/node_modules/lint-staged/package.json
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1141 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'rnTemplate'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:4.2.0.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:4.2.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/4.2.0/gradle-4.2.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/4.2.0/gradle-4.2.0.pom'.
               > dl.google.com:443 failed to respond

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'rnTemplate'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:4.2.0.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:4.2.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/4.2.0/gradle-4.2.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/4.2.0/gradle-4.2.0.pom'.
               > dl.google.com:443 failed to respond

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

**Comment by Atlan8** [comment]
开了翻墙，删掉node_modules文件夹，重新安装依赖，就解决了问题，谢谢大佬

**Comment by chj-damon** [comment]
ok, 反正开发RN项目最恶心的就是拉取一些依赖的资源，总会因为墙的原因失败从而导致项目跑不起来。那我先关掉了
