### ISSUE TITLE
不用swagger怎么前后端怎么做联调?另外"我的"页面报错了

### ISSUE THREAD

**Issue by labike** [thundersdata-frontend/rn-template#37]
后台没用swagger, 应该怎么做联调
```
/**
 * @description login
 */
import * as defs from '../../baseClass';
import { initRequest } from '../../../../common';
import Config from 'react-native-config';

const backEndUrl = Config['authorization'];

// 初始值
export const init = new defs.authorization.ClientConfig();
// 接口地址
export const url = '/auth/login';

export async function fetch(params = {}) {
  const request = await initRequest();
  const result = await request.get(backEndUrl + url, {
    headers: {
      'Content-Type': 'application/json',
    },
    params,
  });
  return result;
}
```

ByronRefreshControl并没有声明和导出

<img width="1269" alt="截屏2022-07-22 下午10 47 16" src="https://user-images.githubusercontent.com/15871933/180464879-929b2d57-526b-4269-88a9-95ef7226b04e.png">

**Comment by chj-damon** [comment]
没有用swagger的话，就把项目里的pontTemplate / pont-config 这两个文件删掉，pacakge.json里面的`@td-design/pont-engine` 也可以删掉。

关于这个插件的报错，我刚才注意到它发了新版本，你重新装一下node_modules看看，我本地看了是没有报错的。

**Comment by chj-damon** [comment]
你们没有用swagger的话，其实可以按照这个api文件夹下的格式自己构造请求。我们这里的是公司自己的规范
