### ISSUE TITLE
热更新

### ISSUE THREAD

**Issue by zxymgl** [thundersdata-frontend/rn-template#41]
大佬，我集成了热更新，ios 可用。安卓调用update_check 时，接口报了304.， 方便指导下我吗。 有偿

**Comment by chj-damon** [comment]
em...这个倒是没有遇到过。 你是直接访问的appcenter还是自己搭的服务器啊？

**Comment by zxymgl** [comment]
已经解决。原因是由于我的服务器，部署在ip地址上面是http协议，安卓需要设置网络协议等级，允许http协议访问

**Comment by chj-damon** [comment]
AndroidManifest里面加一下permission就好了是吧？

**Comment by zxymgl** [comment]
是的
