### ISSUE TITLE
单纯的ReactNative,不用expo,有项目模版吗?

### ISSUE THREAD

**Issue by newcolor1234** [thundersdata-frontend/rn-template#47]
@chj-damon 
我是初学者,想有个简单的环境来运行雷数ui
只自用react-native,不用expo,有这样的项目模板吗?
我现在的环境基本上都是最新的
react-native:0.72.4
react: 18.2.0
Java: 11.0.20
Node: 18
Npm: 9.6.7 
如果没有模版,该怎么做?

**Comment by chj-damon** [comment]
你直接切到library-example这个分支看看

**Comment by chj-damon** [comment]
https://github.com/chj-damon/TDDesignRNExample

看commit，就这几步就好了
